language: ruby
before_install:
 - sudo apt-get install libffi-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
# # update locale settings
# before_install:
#   - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de
notifications:
  slack: carminatiio:ISZOupqjubPs27MjEKBRgdcv
